### ISSUE TITLE
Crash when click play next

### ISSUE THREAD

**Issue by muhammadarif1** [gauravjot/android-noad-music-player#4]
#### EXPECTED BEHAVIOR
user should be able to play next music
#### ACTUAL BEHAVIOR
The app crash when user click "play next"
#### STEP TO REPRODUCE
open the app 
Scroll down to to find list of music
Click dot 3 on any music 
Click "play next"
See error

#### bug recording
https://youtu.be/vnf7snnzrgs

#### LOG CAT
```FATAL EXCEPTION: main
Process: com.droidheat.musicplayer, PID: 18760
java.lang.IndexOutOfBoundsException: Invalid index 1, size is 0
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.add(ArrayList.java:147)
	at com.droidheat.musicplayer.SongsManager.playNext(SongsManager.java:414)
	at com.droidheat.musicplayer.AdapterFiveRecentlyAdded$3.onMenuItemClick(AdapterFiveRecentlyAdded.java:153)
	at android.support.v7.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:113)
	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
	at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1201)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3248)
	at android.widget.AbsListView.onTouchUp(AbsListView.java:4215)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3926)
	at android.support.v7.widget.DropDownListView.onTouchEvent(DropDownListView.java:217)
	at android.support.v7.widget.MenuPopupWindow$MenuDropDownListView.onTouchEvent(MenuPopupWindow.java:129)
	at android.view.View.dispatchTouchEvent(View.java:8593)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2524)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2157)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2530)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
	at android.widget.PopupWindow$PopupViewContainer.dispatchTouchEvent(PopupWindow.java:1799)
	at android.view.View.dispatchPointerEvent(View.java:8799)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4729)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4551)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4047)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4106)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4066)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4209)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4074)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4266)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4047)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4106)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4066)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4074)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4047)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6530)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6504)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6457)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6689)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:218)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:148)
	at android.os.Looper.loop(Looper.java:168)
	at android.app.ActivityThread.main(ActivityThread.java:5657)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:990)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785)```

**Comment by lushohammy** [comment]
where is the description bro?

**Comment by gauravjot** [comment]
Can you confirm your app version by going to settings? This bug shouldn't exist in latest update.

**Comment by muhammadarif1** [comment]
![Screenshot_2019-05-28-06-49-38-39](https://user-images.githubusercontent.com/36690337/58442358-d1c21f80-8114-11e9-9a74-644c4f276f55.png)

**Comment by muhammadarif1** [comment]
Btw i got the app from playstore

**Comment by gauravjot** [comment]
Thank you for follow up but can you please go to Phone Settings > Apps > Noad Player. Also check if there is an available update on Play Store for app.

**Comment by gauravjot** [comment]
Also it seems from log at you provided is that queue is empty which indicates your phone don't have any music files in it. Did you by any chance tried to "Play Next" the  Playlists?

**Comment by gauravjot** [comment]
Okay I have figured out the issue. Will be fixed in next update. I will keep this issue up until updates get through.

**Comment by muhammadarif1** [comment]
![Screenshot_2019-05-28-09-25-54-63](https://user-images.githubusercontent.com/36690337/58446349-a64a2f80-812a-11e9-8f71-43b950b8a000.png)
