### ISSUE TITLE
The app crashed when I tapped multiple times on a song in the playing queue.

### ISSUE THREAD

**Issue by sagorahmed** [gauravjot/android-noad-music-player#8]
#### Expected behavior
I expected that the app could handle itself when I tapped multiple times on a song in the playing queue.

#### Actual behavior
When I tried to click on a song multiple times in my playing queue, then the app crashed. After that, the app is not usable/openable. It crashes every time when I am trying to open it.

#### How to reproduce
Here is every possible detail to reproduce the bug.
1. Open the app.
2. Play a song from the "Songs" tab and open it by taping on that song's name at the downside of your display.
3. Then click on the "list icon/queue button" at the downside of your songs list.
4. Choose a song and tap multiple times on it.
5. Notice the bug. You can't open the app after that crash happened.

* App version: V0.9.4
* Operating system: Android 6.0.1
* Device: Samsung A5

#### Recording Of The Bug
![bug](https://media.giphy.com/media/efbIXbfOksSdjHKtmw/giphy.gif)

#### LogCat
```
06-12 23:39:10.705 25371 25371 E AndroidRuntime: FATAL EXCEPTION: main

06-12 23:39:10.705 25371 25371 E AndroidRuntime: Process: com.droidheat.musicplayer, PID: 25371

06-12 23:39:10.705 25371 25371 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=370; index=-1

06-12 23:39:10.705 25371 25371 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:310)

06-12 23:39:10.705 25371 25371 E AndroidRuntime: 	at com.droidheat.musicplayer.MusicPlayback.doPushPlay(MusicPlayback.java:198)

06-12 23:39:10.705 25371 25371 E AndroidRuntime: 	at com.droidheat.musicplayer.MusicPlayback.access$400(MusicPlayback.java:50)

06-12 23:39:10.705 25371 25371 E AndroidRuntime: 	at com.droidheat.musicplayer.MusicPlayback$1.onSkipToQueueItem(MusicPlayback.java:432)

06-12 23:39:10.705 25371 25371 E AndroidRuntime: 	at android.support.v4.media.session.MediaSessionCompat$Callback$StubApi21.onSkipToQueueItem(MediaSessionCompat.java:1420)

06-12 23:39:10.705 25371 25371 E AndroidRuntime: 	at android.support.v4.media.session.MediaSessionCompatApi21$CallbackProxy.onSkipToQueueItem(MediaSessionCompatApi21.java:213)

06-12 23:39:10.705 25371 25371 E AndroidRuntime: 	at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1219)

06-12 23:39:10.705 25371 25371 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)

06-12 23:39:10.705 25371 25371 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

06-12 23:39:10.705 25371 25371 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7325)

06-12 23:39:10.705 25371 25371 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

06-12 23:39:10.705 25371 25371 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

06-12 23:39:10.705 25371 25371 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by gauravjot** [comment]
I have found the issue and it will be fixed in the next update. Thank you!

**Comment by sagorahmed** [comment]
Hi @gauravjot 
Good to see this bug solved. Thanks for solving it.
